version: 2.1

# Define the jobs  we want to run for this project
jobs:
  build-and-test:
    docker:
      - image: guillemcordoba/rsm
    steps:
      - checkout
      - run:
          name: build-ui
          working_directory: ~/project/ui
          command: |
            NODE_ENV=development npm install
            npm run lint
            npm run build
      - run:
          name: test-ui
          working_directory: ~/project/ui
          command: |
            npm test

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build-and-test
